config/routes.rb
Rails.application.routes.draw do
  resources :contacts, only: [:new, :create]
  resources :notices
  resources :institutions
  resources :categories
  devise_for :users, :path => 'accounts'
  resources :profiles, only: [:index, :show] do
    member do
      get 'authors'
      get 'read_later'
    end
  end
  # resources :users, only: [:index] do
  #   resources :profiles, only: [:index, :show]
  # end
  get "/articles/search", to: "articles#search"

  resources :articles do
    resources :comments, only: [:create, :destroy, :update]
  end
  root 'welcome#index'

  get "/dashboard", to: "welcome#dashboard"
  get "/about", to: "welcome#about"
  put "/articles/:id/publish", to: "articles#publish"
  put "/articles/:id/read_later", to: "articles#mark_as_read_later"
  put "/notices/:id/publish", to: "notices#publish"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/partials/_footer_about.html.erb
<footer class="single single-page without-readmore">
  <div class="container">
    <div class="col-sm-12">
      <p>A Americanae Iurisdictio - Ateneo sobre historia critica del derecho - <%= link_to "Volvé al Inicio", root_path %></p>
    </div>
  </div>
</footer>

app/views/partials/_footer_art.html.erb
<footer class="single">
	<div class="container">
		<div class="row">
			<div class="col-xs-12 col-sm-2">
				<% if @article.user.avatar.exists? %>
					<%= image_tag(@article.user.avatar, class: "user-icon") %>
				<% else %>
					<%= image_tag(@article.user.gravatar, class: "user-icon") %>
				<% end %>
			</div>
			<div class="col-xs-12 col-sm-6">
			  <div class="category-list">
			    <p>Publicado el <span><%= @article.created_at.to_formatted_s(:long) %></span></p>
			    <p><%= link_to @article.user.profile.full_name, @article.user.profile %> in <%= link_to @article.categories.first.name, @article.categories.first if @article.categories.any? %></p>
			    <div class="other-catergories">
			      <h3>Tambien publicado en</h3>
			      <ul>
			      	<% @article.categories.each do |category|%>
								<li><%= link_to category.name, category %></li>
							<% end %>
			      </ul>
			    </div>
			  </div>
			</div>
			<div class="col-xs-12 col-sm-4">
				<div class="social">
				    <p>Comparte este articulo</p>
				    <div class="social-links">
				        <a class="social-icon" href="#" data-platform="twitter" data-message="Message about this post" data-url="http://writertheme.com/post"><i class="fa fa-twitter"></i></a>

				        <a class="social-icon" href="#" data-platform="facebook" data-message="Message about this post" data-url="http://writertheme.com/post"><i class="fa fa-facebook-official"></i></a>

				        <a class="social-icon" data-platform="mail" href="mailto:hernan.bordon@gmail.com"><i class="fa fa-envelope"></i></a>
				    </div>
				</div>
			</div>
		</div><!-- en row -->
	</div><!-- end container-->
</footer>

app/views/partials/_joius.html.erb
<div class="jumbotron" style="background-color: rgba(0,0,0,0.6);">
	<div class="primary-info">
		<h1>Nueva Historia del Derecho</h1>
		<p style="font-size: 10px;">Ateneo de Historia Critica del Derecho, Historia Social de la Justicia y Antropología Histórica.</p> 
		<p><a href="">Mira nuestros artículos.</a></p>

		<p>Scientia est content</p>
	</div>
	<div class="secondary-info">
		<p>
			<a class="btn btn-primary" href=""><i class="fa fa-user-plus"></i>Newsletter</a>
		</p>
	</div>
</div>

app/views/partials/_loguedusermenu.html.erb
<div class="col-md-6 sub-nav align-links-nav-rigth">
  <% if !current_user.nil? %>
    <%= link_to "Cerrar Sesión", destroy_user_session_path, method: :delete, class: "item-nav-rigth" %>
    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= image_tag(current_user.avatar, class: "user-topnav-icon dropdown-toggle") %> <span class="caret"></span></a>
    <ul class="dropdown-menu-right">
      <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
      <li><a href="#">Another action</a></li>
      <li><a href="#">Something else here</a></li>
      <li role="separator" class="divider"></li>
      <li><a href="#">Separated link</a></li>
      <li role="separator" class="divider"></li>
      <li><a href="#">One more separated link</a></li>
    </ul>
  <% else %>
    <%= link_to "Sign Up", new_user_registration_path, class: "item-nav-rigth" %>
    <%= link_to "Login", new_user_session_path, class: "item-nav-rigth" %>
  <% end -%>
</div>

app/views/partials/_main_menu.html.erb
<div class="collapse navbar-collapse">
  <ul class="nav nav-pills navbar-nav">
    
      <%# <li class="dropdown active">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#">
              Blog 
              <b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
              <li><a href="#">Blog</a></li>
              <li><a href="#">Blog Detail</a></li>
          </ul>
      </li> %>
      <li>
          <a href="">About</a>
      </li>
      <% if !current_user.nil? %>
        <li>
          <%= link_to new_article_path do %>
            <i class="fas fa-file-contract"></i> Subí un Artículo
          <% end %>
        </li>
        <li class="dropdown active">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#">
            <%= current_user.avatar.exists? ? image_tag(current_user.avatar, class: "user-topnav-icon") : image_tag(current_user.gravatar, class: "user-topnav-icon" ) %>
            <b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
            <li>
              <%= link_to edit_user_registration_path do %>
                <i class="fas fa-user"></i> Edita tu Perfil
              <% end %>
            </li>
            <li>
              <%= link_to new_article_path do %>
                <i class="fas fa-file-contract"></i> Subí un Artículo
              <% end %>
            </li>
            <li role="separator" class="divider"></li>
              <% if !current_user.nil? && current_user.is_admin? %>
                <li>
                  <%= link_to dashboard_path do %>
                    <i class="fas fa-user-tie"></i> Admin Dashboard
                  <% end %>
                </li>
              <% end -%>
            <li role="separator" class="divider"></li>
            <li><%= link_to "Cerrar Sesión", destroy_user_session_path, method: :delete %></li>
          </ul>
        </li>
      <% else %>
        <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <li><%= link_to "Login", new_user_session_path %></li>
      <% end %>                       
  </ul>
</div>

app/views/partials/_navigation.html.erb
<nav class="navbar navbar-toggleable-md navbar-light bg-faded">
	<button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <%= link_to "Historia y Derecho", root_path, class: "navbar-brand" %>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
	  <ul class="navbar-nav mr-auto">

	    <li class="nav-item active">
	      <%= link_to "Atricles", articles_path, class:"nav-link" %>
	    </li>
	    <li class="nav-item dropdown">
	    	<a class="nav-link dropdown-toggle" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown link
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
			    <% @categories.each do |category| %>
				      <%= link_to category.name, category, class:"dropdown-item" %>
			    <% end -%>
		    </div>
	    </li>
	    <li class="nav-item">
	    	<a class="nav-link" href="movies/new">New Movie <span class="sr-only">(current)</span></a>
	    </li>
	    <% if user_signed_in? %>
				<li class="nav-item">
					<%= link_to "Cerrar Sesión", destroy_user_session_path, method: :delete, class:"nav-link" %>
				</li>
			<% else %>
				<li class="nav-item">
					<%= link_to "Iniciar Sesión", new_user_session_path, class:"nav-link" %>
				</li>
				<li class="nav-item">
					<%= link_to "Crear Cuenta", new_user_registration_path, class:"nav-link" %>
				</li>
		<% end %>
	  </ul>
	  <form class="form-inline pull-xs-right">
	    <input class="form-control" type="text" placeholder="Search">
	    <button class="btn btn-success-outline" type="submit">Search</button>
	  </form>
  </div>
</nav>

app/views/partials/_notices_wellcome.html.erb
<div class="aside-widget">
  <header>
    <h3>Noticias</h3>
  </header>
  <div class="body">
    <ul class="tales-list">
      <% @notices.each do |notice| %>
        <li>
          <%= link_to notice.title, notice %></br>
          <h6><%= notice.body %></h6>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/partials/_sectionHome.html.erb
<section class="sidebar col-md-5 col-sm-12" style="background-color: rgb(128, 255, 229); left: 0px;">
  <span class="menu-trigger animated fadeInDown">
      <span class="bar"></span>
      <span class="bar"></span>
      <span class="bar"></span>
  </span>
  <div class="site-info">
    <% if @enable_joinus %>
      <%= render "partials/joius" if @enable_joinus %>
    <% else %>
      <div class="primary-info">
        <h1><%= @category.name %></h1>
        <p>Descripcion de la categoria</p>
      </div>
    <% end -%>
  </div>
</section><!--end sidebar-->

app/views/partials/_sidebarnav.html.erb
<div id="menu-target">
  <ul>
    <li><i class="fa fa-home"></i><%= link_to "Home", root_path, id: 'ClearActive' %></li>
    <li><i class="fa fa-users"></i><%= link_to "Equipo Editorial", profiles_path %></li>
    <% if current_user %>
      <li> <i class="fa fa-user"></i><%= link_to "Autores", authors_profile_path(current_user.id) %> </li>
    <% end %>
    <li><i class="fa fa-anchor"></i><%= link_to "Quienes somos", about_path %><a href="">About</a></li>
    <li><i class="fa fa-star"></i><a href="">Favorites</a></li>
    <li><i class="fa fa-paper-plane"></i><%= link_to "Contactenos", new_contact_path %></li>
  </ul>
  <hr>
  <ul>
    <li><i class="fa fa-file"></i><a href="">Post Page</a></li>
    <li><i class="fa fa-file"></i><a href="">Post with Sidebar</a></li>

    <li><i class="fa fa-home"></i><a href="">Alternate Home</a></li>
    <li><i class="fa fa-image"></i><a href="">Category Page</a></li>
  </ul>
    <% if !current_user.nil? && current_user.is_admin? %>
      <hr>
      <ul>
        <li><i class="fa fa-user-o"></i><%= link_to "Admin Dashboard", dashboard_path %></li>
      </ul>
    <% end -%>
</div>

app/views/partials/_sub-nav.html.erb
<div class="col-md-6 sub-nav">
	<%= link_to root_path do %>
		<i class="fa fa-home"></i>
	<% end -%>
  <%= link_to "Artículos", articles_path, class:"select-posts", id: "art", remote: true %>
  <%= link_to "Categorias", categories_path, class:"select-categories", id:"carga", remote: true %>
</div>
<div class="col-md-6 sub-nav align-links-nav-rigth">
  <div class="col-md-9">
  <%= form_tag(articles_search_path, :method => "get", class: "search-form", id: "search-form") do %>
    <div class="form-group has-feedback">
      <label for="search" class="sr-only">Search</label>
      <%= text_field_tag :query, params[:query], placeholder: "Search", class: "form-control-1", name:"query" %>
        <span class="glyphicon glyphicon-search form-control-feedback"></span>
    </div>
  <% end %>
  </div>
  <div class="col-md-3">
    <% if !current_user.nil? %>
      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.avatar.exists? ? image_tag(current_user.avatar, class: "user-topnav-icon dropdown-toggle") : image_tag(current_user.gravatar, class: "user-topnav-icon dropdown-toggle") %> <span class="caret"></span></a>
      <ul class="dropdown-menu pull-right">
        <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
        <li><%= link_to "Publica un Articulo", new_article_path %></li>
        <li role="separator" class="divider"></li>
        <li><%= link_to "Read Later", read_later_profile_path(current_user) %></li>
        <li role="separator" class="divider"></li>
        <li><%= link_to "Cerrar Sesión", destroy_user_session_path, method: :delete, class: "item-nav-rigth" %></li>
      </ul>
    <% else %>
      <%= link_to "Login", new_user_session_path, class: "item-nav-rigth" %>
    <% end -%>
  </div>  
</div>
<%# <div class="col-md-6 sub-nav align-links-nav-rigth">
  
</div> %>