config/routes.rb
Rails.application.routes.draw do
  resources :contacts, only: [:new, :create]
  resources :notices
  resources :institutions
  resources :categories
  devise_for :users, :path => 'accounts'
  resources :profiles, only: [:index, :show] do
    member do
      get 'authors'
      get 'read_later'
    end
  end
  # resources :users, only: [:index] do
  #   resources :profiles, only: [:index, :show]
  # end
  get "/articles/search", to: "articles#search"

  resources :articles do
    resources :comments, only: [:create, :destroy, :update]
  end
  root 'welcome#index'

  get "/dashboard", to: "welcome#dashboard"
  get "/about", to: "welcome#about"
  put "/articles/:id/publish", to: "articles#publish"
  put "/articles/:id/read_later", to: "articles#mark_as_read_later"
  put "/notices/:id/publish", to: "notices#publish"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="js svg jPanelMenu">
  <head>
    <title>NHD</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Google fonts -->
		<%# <link href="https://fonts.googleapis.com/css?family=Lato:400,400i,700,900" rel="stylesheet"> %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,600%7CPT+Serif:400,400italic" rel="stylesheet" type="text/css">

    <!-- Google Analytics script -->
    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-98875330-1', 'auto');
      ga('send', 'pageview');

    </script>
  </head>

  <body data-menu-position="closed">
    <header>
        <div class="widewrapper masthead">
            <div class="container">
                <a href="#" id="logo">
                    Nueva Historia del Derecho 
                    <span class="copete_logo">
                        <p>Ateneo de Historia Critica del Derecho, </p>
                        <p>Historia Social de la Justicia y</p> 
                        <p>Antropología Histórica.</p>
                    </span>
                    <!--Use the following line instead if you want to use an image logo-->
                    <!--<img src="img/tales-logo.png" alt="Tales Blog">-->
                </a>

                <div id="mobile-nav-toggle" class="pull-right">
                    <a href="#" data-toggle="collapse" data-target=".tales-nav .navbar-collapse">
                        <i class="fa fa-bars"></i>
                    </a>
                </div>

                <nav class="pull-right tales-nav">
                    <%= render "partials/main_menu"%>
                </nav>        

            </div>
        </div>

        <div class="widewrapper subheader">
            <div class="container">
                <div class="tales-breadcrumb">
                    <%= link_to root_path do %>
                        <i class="fas fa-home"></i>
                    <% end %>
                    
                </div>

                <div class="tales-searchbox">
                    <%= form_tag(articles_search_path, :method => "get", id: "search-form") do %>
                        <%= button_tag(type:"submit", class:"searchbutton") do %>
                            <i class="fa fa-search"></i>
                        <% end %>
                        <%= text_field_tag :query, params[:query], placeholder: "Search", class: "searchfield", id:"searchbox", name:"query" %>
                    <% end %>
                </div>
            </div>
        </div>
    </header>
    <div class="widewrapper main">
        <div class="container">
            <div class="row">
                <%= yield %>
            </div>
        </div>
    </div>
    <footer>
      <div class="widewrapper footer">
        <div class="container">
            <div class="row">
                <div class="col-md-4 footer-widget">
                    <h3> <i class="fab fa-wpforms"></i>  Estadísticas</h3>

                    <span>Muchas veces nosotros tambien perdemos la cantidad de artículo que tenemos aqui. Esto ayuda:</span>

                    <div class="stats">
                        <div class="line">
                            <span class="counter"> <%= Article.count %> </span>
                            <span class="caption"><%= link_to "Articulos", articles_path %></span>
                        </div>
                        <div class="line">
                            <span class="counter"> <%= Comment.count %> </span>
                            <span class="caption">Comentarios</span>
                        </div>
                        <div class="line">
                            <span class="counter"> <%= Profile.count %> </span>
                            <span class="caption"> <%= if Profile.count > 1
                                link_to "Autores", profiles_path
                            else
                                link_to "Autor", profiles_path
                            end %> </span>
                        </div>                    
                    </div>
                </div>
                <div class="col-md-4 footer-widget">
                    <h3> <i class="fas fa-trophy"></i> Salon de la Fama </h3>
                    <ul class="tales-list">
                        <% @most_popular.each do |article| %>
                            <li> <%= link_to article.title.truncate(50, separator:' ', omission:'...(leer)'), article %> </li>
                        <% end %>
                    </ul>
                </div>
                <div class="col-md-4 footer-widget">
                    <h3> <i class="fa fa-envelope"></i>Contactanos</h3>

                    <span>Puedes escribirnos con tus dudas, inquietudes o recomendaciones. Estamos ansiosos de poder conocerte!</span>
                    
                    <span class="email">
                        <a href="#">nhd@infonhd.com</a>
                    </span>
                </div>
            </div>
        </div>
      </div>
      <div class="widewrapper copyright">
        <div class="container">
            <!--Note: Feel free to remove or change this link as you please. A link to HackerThemes is not required by any means-->
            Designed by <a href="#" rel="nofollow">NHD_Design</a>
        </div>
      </div>
    </footer>

  </body>
</html>

app/views/layouts/article_lay.html.erb
<!DOCTYPE html>
<html class="js svg jPanelMenu">
  <head>
    <title>Iurisdictio</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
		<link href="https://fonts.googleapis.com/css?family=Lato:400,400i,700,900" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body data-menu-position="closed">
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %> alert-dismissable">
          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
          <%= value %>
      </div>
    <% end %>
    <!-- if the user has javascript disabled they can still use the menu -->
    <!-- aqui se genera div class="jPanelMenu-panel" -->
      <header class="hero-image" role="banner" style="background-image:url(<%= @enable_joinus ? asset_path('guamanpoma.jpg') : @article.cover.url %>);">

        <span class="menu-trigger animated fadeInDown">
            <span class="bar"></span>
            <span class="bar"></span>
            <span class="bar"></span>
        </span>
        <%= render "partials/sidebarnav" %>
      </header>
      <nav class="hidden-nav navbar navbar-default">
        <div class="container-fluid">
          <div class="navbar-header">
            <a href="" class="navbar-brand">
              <%= image_tag @article.cover.url, class: "user-topnav-icon" %>
            </a>
          </div>
          <ul class="nav navbar navbar-left">
            <li>
              <%= link_to root_path do %>
                <i class="fa fa-home"> Home </i>
              <% end -%>
            </li>
            <li><%= link_to @article.user.profile.full_name, @article.user.profile %></li>
            <li><i class="fa fa-bookmark"> <%= link_to "Read Later", "/articles/#{@article.id}/read_later", method: :put %> </i></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li class="dropdown">
              <% if !current_user.nil? %>
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.avatar.exists? ? image_tag(current_user.avatar, class: "user-topnav-icon") : image_tag(current_user.gravatar, class: "user-topnav-icon") %> <span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
                  <li><%= link_to "Publica un Articulo", new_article_path %></li>
                  <li><%= link_to "Editar este Artículo", edit_article_path(@article) %></li>
                  <li role="separator" class="divider"></li>
                  <li><%= link_to "Cerrar Sesión", destroy_user_session_path, method: :delete, class: "item-nav-rigth" %></li>
                </ul>
              <% else %>
                <%= link_to "Login", new_user_session_path, class: "item-nav-rigth" %>
              <% end -%>
            </li>
          </ul>
        </div>
      </nav>
      <main class="container">
        <div class="row">
          <%= yield %>
        </div>
      </main>

      <% if !@enable_joinus %>
        <%= render "partials/footer_art" %>
      <% else %>
        <%= render "partials/footer_about" %>
      <% end -%>
    <style id="jPanelMenu-style-master">body{width:100%}.jPanelMenu,body{overflow-x:hidden}#jPanelMenu-menu{display:block;position:fixed;top:0;left:0;height:100%;z-index:-1;overflow-x:hidden;overflow-y:scroll;-webkit-overflow-scrolling:touch}.jPanelMenu-panel{position:static;left:0;top:0;z-index:2;width:100%;min-height:100%;background:rgb(255, 255, 255)}</style>

    <script>
      //caches a jQuery object containing the header element
      $(function(){
        var puto = $(".hidden-nav");
        console.log("-------------------- putooo!!");
        $(window).scroll(function() {
          console.log("----------- entro en windows scroll");
          var scroll = $(window).scrollTop();

          if (scroll >= 500) {
            console.log("--------- entro al if");
            puto.addClass("show");
          } else {
            puto.removeClass("show");
          }
        });
      });
    </script>
  </body>
</html>